package br.com.emailmanager.webservice.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthenticationServerService", targetNamespace = "http://webservice.emailmanager.com.br/", wsdlLocation = "http://localhost:8080/Authentication?wsdl")
public class AuthenticationServerService extends Service {

	private final static URL AUTHENTICATIONSERVERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(br.com.emailmanager.webservice.cliente.AuthenticationServerService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = br.com.emailmanager.webservice.cliente.AuthenticationServerService.class
					.getResource(".");
			url = new URL(baseUrl, "http://localhost:8080/Authentication?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/Authentication?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		AUTHENTICATIONSERVERSERVICE_WSDL_LOCATION = url;
	}

	public AuthenticationServerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AuthenticationServerService() {
		super(AUTHENTICATIONSERVERSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.emailmanager.com.br/",
				"AuthenticationServerService"));
	}

	/**
	 * 
	 * @return returns AuthenticationServer
	 */
	@WebEndpoint(name = "AuthenticationServerPort")
	public AuthenticationServer getAuthenticationServerPort() {
		return super.getPort(new QName(
				"http://webservice.emailmanager.com.br/",
				"AuthenticationServerPort"), AuthenticationServer.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns AuthenticationServer
	 */
	@WebEndpoint(name = "AuthenticationServerPort")
	public AuthenticationServer getAuthenticationServerPort(
			WebServiceFeature... features) {
		return super.getPort(new QName(
				"http://webservice.emailmanager.com.br/",
				"AuthenticationServerPort"), AuthenticationServer.class,
				features);
	}

}
