
package br.com.emailmanager.webservice.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthenticationServer", targetNamespace = "http://webservice.emailmanager.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationServer {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.cliente.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.cliente.SendEmailResponse")
    public void sendEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.cliente.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.cliente.AuthenticateResponse")
    public void authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
