
package br.com.emailmanager.webservice.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationServer", targetNamespace = "http://webservice.emailmanager.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationServer {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveNewUser", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.SaveNewUser")
    @ResponseWrapper(localName = "saveNewUserResponse", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.SaveNewUserResponse")
    @Action(input = "http://webservice.emailmanager.com.br/AuthenticationServer/saveNewUserRequest", output = "http://webservice.emailmanager.com.br/AuthenticationServer/saveNewUserResponse")
    public void saveNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.SendEmailResponse")
    @Action(input = "http://webservice.emailmanager.com.br/AuthenticationServer/sendEmailRequest", output = "http://webservice.emailmanager.com.br/AuthenticationServer/sendEmailResponse")
    public void sendEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.AuthenticateResponse")
    @Action(input = "http://webservice.emailmanager.com.br/AuthenticationServer/authenticateRequest", output = "http://webservice.emailmanager.com.br/AuthenticationServer/authenticateResponse")
    public Boolean authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns br.com.emailmanager.webservice.cliente.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthenticateUser", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.GetAuthenticateUser")
    @ResponseWrapper(localName = "getAuthenticateUserResponse", targetNamespace = "http://webservice.emailmanager.com.br/", className = "br.com.emailmanager.webservice.cliente.GetAuthenticateUserResponse")
    @Action(input = "http://webservice.emailmanager.com.br/AuthenticationServer/getAuthenticateUserRequest", output = "http://webservice.emailmanager.com.br/AuthenticationServer/getAuthenticateUserResponse")
    public User getAuthenticateUser();

}
