package EmailBoxServer;


/**
* EmailBoxServer/Email_Box_ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/com/emailmanager/corba/EmailBoxServer.idl
* Terça-feira, 25 de Novembro de 2014 10h17min40s BRST
*/

public interface Email_Box_ServerOperations 
{
  void salvarEmail (int userId, String toEmail, String messageEmail);
  String consultarEmail (int userId, String date);
} // interface Email_Box_ServerOperations
