package EmailBoxServer;


/**
* EmailBoxServer/Email_Box_Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/com/emailmanager/corba/EmailBoxServer.idl
* Terça-feira, 25 de Novembro de 2014 10h17min40s BRST
*/

public interface Email_Box_Server extends Email_Box_ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Email_Box_Server
