package EmailBoxServer;


/**
* EmailBoxServer/Email.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/com/emailmanager/corba/EmailBoxServer.idl
* Quinta-feira, 27 de Novembro de 2014 10h32min11s BRST
*/

public final class Email implements org.omg.CORBA.portable.IDLEntity
{
  public int emailId = (int)0;
  public String Message = null;
  public String To = null;
  public String From = null;

  public Email ()
  {
  } // ctor

  public Email (int _emailId, String _Message, String _To, String _From)
  {
    emailId = _emailId;
    Message = _Message;
    To = _To;
    From = _From;
  } // ctor

} // class Email
