package EmailBoxServer;


/**
* EmailBoxServer/Email.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/com/emailmanager/corba/EmailBoxServer.idl
* Quarta-feira, 26 de Novembro de 2014 10h30min08s BRST
*/

public final class Email implements org.omg.CORBA.portable.IDLEntity
{
  public String Message = null;
  public String To = null;
  public String From = null;

  public Email ()
  {
  } // ctor

  public Email (String _Message, String _To, String _From)
  {
    Message = _Message;
    To = _To;
    From = _From;
  } // ctor

} // class Email
