package EmailBoxServer;


/**
* EmailBoxServer/Email_Box_ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/com/emailmanager/corba/EmailBoxServer.idl
* Quinta-feira, 27 de Novembro de 2014 10h32min11s BRST
*/

public interface Email_Box_ServerOperations 
{
  void saveEmail (int userId, String toEmail, String messageEmail);
  EmailBoxServer.Email[] getEmails (int userId, String date);
  void deleteEmail (int emailId);
} // interface Email_Box_ServerOperations
