package EmailBoxServer;


/**
* EmailBoxServer/Email_Box_ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/heloisa.kopsch/git/sistemasdistribuidos/SistemasDistribuidos/src/br/com/emailmanager/corba/EmailBoxServer.idl
* Segunda-feira, 24 de Novembro de 2014 10h20min38s BRST
*/

public interface Email_Box_ServerOperations 
{
  void salvarEmail ();
  String consultarEmail ();
} // interface Email_Box_ServerOperations
