module EmailBoxServer{

struct Email
{
   string Message;
   string To;
   string From;
};

typedef sequence<Email> Emails;


	interface Email_Box_Server {

		void saveEmail(in long userId, in string toEmail, in string messageEmail);

		Emails getEmails(in long userId, in string date);
	};
};
