module EmailBoxServer{


	interface Email_Box_Server {

		void salvarEmail(in long userId, in string toEmail, in string messageEmail);

		string consultarEmail(in long userId, in string date);
	};


};
